### ISSUE TITLE
Fehlermeldung nach Installation in Contao 4.6

### ISSUE THREAD

**Issue by seibtph** [heimrichhannot/contao-api-bundle#1]
Nach der Installation in Contao 4.7 erhalte ich folgende Fehlermeldung. Funktioniert sie denn überhaupt schon in Contao 4.7?

`Cannot autowire service "huh.utils.container": argument "$scopeMatcher" of   
  method "HeimrichHannot\UtilsBundle\Container\ContainerUtil::__construct()"   
  references class "Contao\CoreBundle\Routing\ScopeMatcher" but no such servi  
 ce exists. You should maybe alias this class to the existing "contao.routin  
  g.scope_matcher" service.`

**Comment by koertho** [comment]
@seibtph In Contao 4.7.5 tritt der Fehler nicht auf, nutzt du hier schon die aktuellste Version? Das war ein Fehler mit 4.6, aber eben auf Core-Seite.

**Comment by seibtph** [comment]
@koertho Du hast recht. Ich hatte auch gar nicht Contao 4.7 installiert, sondern noch 4.6, da hatte ich mich vertan. Installation hat jetzt geklappt, einen Fehler bei der Installation hatte ich aber noch, ich habe dafür mal einen Pull Request angelegt.
