### ISSUE TITLE
composer-error bei installaltion in >= contao 4.8

### ISSUE THREAD

**Issue by srhinow** [heimrichhannot/contao-api-bundle#11]
Das Paket bzw meine Erweiterung die auf contao-api-bundle beruht, kann nicht installiert werden da contao-api-bundle  -> symfony/framework-bundle: ^3.4 required es wird aber z.B. in Contao4.8 mind -> symfony/framework-bundle:4.3.9 benötigt.

Hier ein kleiner Auszug aus dem composer error

` Conclusion: don't install symfony/framework-bundle v4.3.9|install symfony/framework-bundle v3.4.38
    - vendor/mein-bundle dev-CSM-67 requires heimrichhannot/contao-api-bundle ^2.0 -> satisfiable by heimrichhannot/contao-api-bundle[2.0.0, 2.0.1, 2.0.2].
    - heimrichhannot/contao-api-bundle 2.0.0 requires symfony/framework-bundle ^3.4 -> satisfiable by symfony/framework-bundle[v3.4.0, v3.4.0-BETA1, v3.4.0-BETA2,`

**Comment by koertho** [comment]
Das ist eigentlich schon behoben.
