### ISSUE TITLE
Abhängigkeitskonflikt mit aktuellen erweiterungen.

### ISSUE THREAD

**Issue by srhinow** [heimrichhannot/contao-api-bundle#12]
Die aktuelle Version 2.0 von legito/api-wrapper setzt php
heimrichhannot/contao-api-bundle  firebase/php-jwt[v5.2.0] vorraus. contao-api-bundle verlangt aber ne alte Version ^4.0

**Comment by koertho** [comment]
Fixed in 4195b45d57ca2a56195c783107e58d8b6be186ad
