### ISSUE TITLE
Features und Fixes im Fork

### ISSUE THREAD

**Issue by srhinow** [heimrichhannot/contao-api-bundle#14]
In meinem Fork https://gitlab.com/srhinow/contao-api-bundle/-/tree/2.2.0 habe ich verschiedene Fehler gefixt. Außerdem kann man sich jetzt auch bei den Events (calendar_events) und News (contao_news) die enthaltenen Inhaltselemente aus der tl_content mit ausgeben lassen. In SHOW ist es automatisch unter 'content' mit bei. In der LIST kann man diese zusätzliche Ausgabe von 'content' auch per GET-Parameter &content=1 anschalten. Außerdem habe ich auch Resources für Faq (contao_faq) und Newsletter (contao_newsletter) angelegt.

Wäre schön wenn du diese Änderungen und zusätzlichen Funktionen mit in dein Repo mit aufnehmen könntest.

**Comment by koertho** [comment]
@srhinow Hi, mach am besten mal einen PR. Wir sind bei diesem Bundle hier leider nicht so hinterher, da wir es selber wenig einsetzen.

**Comment by srhinow** [comment]
nen PR von gitlab nach github? Wie geht das?

**Comment by koertho** [comment]
Keine Ahnung, ob sowas geht. Eventuell könntest du deine Repo in Github einstellen und dann den PR machen.

**Comment by theDyingMountain** [comment]
@koertho @srhinow Wie ist hier der Stand? Die neuen Features klingen interessant.

**Comment by koertho** [comment]
@theDyingMountain Habe noch nichts neues gehört. Nutzt ihr das Bundle aktiv?

**Comment by theDyingMountain** [comment]
@koertho nein noch nicht, aber wir haben jetzt ein Projekt wo Contao mit einem anderen System kommunizieren muss und brauchen daher die Schnittstelle.

**Comment by koertho** [comment]
@theDyingMountain Du kannst es dir gerne anschauen. Ich stecke da aber gar nicht drin und ich kenne auch kein Projekt, wo das aktuell eingesetzt wird, kann daher auch nicht wirklich Hilfestellung anbieten.
