### ISSUE TITLE
Error: Attempted to load class "Category" from namespace "HeimrichHannot\CategoriesBundle\Backend"

### ISSUE THREAD

**Issue by ReDeLe-design** [heimrichhannot/contao-api-bundle#15]
contao Version:  4.9.30
contao-api-bundle: 2.2.3

After click on API/Anwendung the followig Error occurs:
Attempted to load class "Category" from namespace "HeimrichHannot\CategoriesBundle\Backend". Did you forget a "use" statement for "SimplePie\Category"?

CategoriesListener.php seems to use it:
  "use HeimrichHannot\CategoriesBundle\Backend\Category;"

but no dependency seems to exist.

**Comment by koertho** [comment]
@ReDeLe-design There was an issue, could you please test if the latest commit fix the error?

**Comment by ReDeLe-design** [comment]
This error is fixed. But i found an other. See next Issue.
