### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by Helrunar** [heimrichhannot/contao-api-bundle#3]
Hallo,

nachdem ich das Modul zuerst erfolgreich zum Laufen bekommen habe, habe ich eine eigene Resource angelegt, welche ich über die Url auch ansprechen kann. Nun komme ich aber nicht mehr auf die backendseite des Moduls (was am Anfang, nach Anlegen der Resource) noch funktioniert hat. Im Backend erscheint folgende Meldung:

> Attempted to load class "huh.filter.backend.filter_config_element" from the global namespace. Did you forget a "use" statement?

Im Log des Servers folgendes:
> [proxy_fcgi:error] [pid 1359] [client 192.168.1.181:60560] AH01071: Got error 'PHP message: PHP Warning:  in_array() expects parameter 2 to be array, null given in /www.lsync/contao/vendor/contao/core-bundle/src/Resources/contao/library/Contao/System.php on line 165\nPHP message: PHP Stack trace:\nPHP message: PHP   1. {main}() /www.lsync/contao/web/app.php:0\nPHP message: PHP   2. Contao\\ManagerBundle\\HttpKernel\\ContaoCache->handle() /www.lsync/contao/web/app.php:38\nPHP message: PHP   3. Contao\\ManagerBundle\\HttpKernel\\ContaoCache->handle() /www.lsync/contao/vendor/friendsofsymfony/http-cache/src/SymfonyCache/EventDispatchingHttpCache.php:98\nPHP message: PHP   4. Contao\\ManagerBundle\\HttpKernel\\ContaoCache->pass() /www.lsync/contao/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpCache/HttpCache.php:183\nPHP message: PHP   5. Contao\\ManagerBundle\\HttpKernel\\ContaoCache->forward() /www.lsync/contao/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpCache/HttpCache.php:238\nPHP message: PHP   6. Contao\\ManagerBundle\\HttpKernel\\ContaoCache->forward() /www.lsync/contao/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/HttpCache/HttpCache.php:57\nPHP message: PHP   7. Symfony\\Component\\HttpKernel\\HttpCache\\SubRequestHandler::handle() /www.lsync/contao/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpCache/HttpCache.php:448\nPHP message: PHP   8. Contao\\ManagerBundle\\HttpKernel\\ContaoKernel->handle() /www.lsync/contao/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpCache/SubRequestHandler.php:102\nPHP message: PHP   9. Symfony\\Component\\HttpKernel\\HttpKernel->handle() /www.lsync/contao/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:200\nPHP message: PHP  10. Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw() /www.lsync/contao/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:68\nPHP message: PHP  11. Contao\\CoreBundle\\Controller\\BackendController->mainAction() /www.lsync/contao/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:151\nPHP message: PHP  12. Contao\\BackendMain->run() /www.lsync/contao/vendor/contao/core-bundle/src/Controller/BackendController.php:55\nPHP message: PHP  13. Contao\\BackendMain->getBackendModule() /www.lsync/contao/vendor/contao/core-bundle/src/Resources/contao/controllers/BackendMain.php:132\nPHP message: PHP  14. Contao\\DC_Table->showAll() /www.lsync/contao/vendor/contao/core-bundle/src/Resources/contao/classes/Backend.php:619\nPHP message: PHP  15. Contao\\DC_Table->listView() /www.lsync/contao/vendor/contao/core-bundle/src/Resources/contao/drivers/DC_Table.php:358\nPHP message: PHP  16. Contao\\DC_Table->generateButtons() /www.lsync/contao/vendor/contao/core-bundle/src/Resources/contao/drivers/DC_Table.php:4934\nPHP message: PHP  17. Contao\\DC_Table->import() /www.lsync/contao/vendor/contao/core-bundle/src/Resources/contao/classes/DataContainer.php:792\nPHP message: PHP  18. in_array() /www.lsync/contao/vendor/contao/core-bundle/src/Resources/contao/library/Contao/System.php:165\n'

Ein wieder Rückgängig machen meiner Änderungen in meinem Modul erzielt keinen Effekt. Deinstallieren und neu Installieren hilft kurzfristig, dann tritt der Fehler wieder auf. Das verwendete Contao ist in der Version 4.4.40

**Comment by fatcrobat** [comment]
Ist der Service denn in der service.yml registriert? Andernfalls vermute ich ist die Klasse dem composer Autoloader nicht bekannt, einfach mal composer dumpautoload in der Konsole aufrufen.

**Comment by Helrunar** [comment]
Ja, Service ist registriert und der Autoloader aktualisiert. Arbeite nicht zum ersten mal mit Composer ;-)

**Comment by Helrunar** [comment]
So, nach nun mehrfachen versuchen kann ich sagen, bei mir funktioniert die Version 2 wirklich nicht. Autoloader neu generieren und Cache leeren zeigt keinen Effekt. Zu Testzwecken die Version 2 deinstalliert und auf Version 1 gewechselt: Funktioniert und ich kann meine Resource im Backend auswählen. Update von Version 1 auf 2: Gleiche Fehlermeldung wie oben schon gepostet.

Warum wurde das Ticket geschlossen?

**Comment by fatcrobat** [comment]
Prüfen wir, sah erst nach einem autoloader Fehler aus.

**Comment by Helrunar** [comment]
Vielen Dank :-) Ich werde parallel auch nochmal den Debugger anschmeißen. Ich habe zumindest schon rausgefunden, dass im Backend mein Service geladen wird, nur bis zum Punkt, wo ausgestiegen wird, bin ich noch nicht gekommen. Muss das ganze mal ohne den Cache debuggen

**Comment by Helrunar** [comment]
Erster Fortschritt: in dca/tl_api_app.php ist folgendes unter operations aufgeführt

`'toggle' => [
                'label'           => &$GLOBALS['TL_LANG']['tl_api_app']['toggle'],
                'icon'            => 'visible.gif',
                'attributes'      => 'onclick="Backend.getScrollOffset();return AjaxRequest.toggleVisibility(this,%s)"',
                'button_callback' => ['huh.filter.backend.filter_config_element', 'toggleIcon'],
            ],`

Den Service für den callback gibt es jedoch nicht (weder in Version 1.0.2, noch in Version 2). Kommentiere ich diese Stelle aus, so läuft das Modul im Backend wieder. Davon unberührt bleibt jedoch das Ticket https://github.com/heimrichhannot/contao-api-bundle/issues/4. Unter Version 2 bekomme ich meinen Service dennoch nicht angezeigt im Dropdown

**Comment by srhinow** [comment]
bei mir ist dasselbe Problem
