### ISSUE TITLE
composer bemängelt Version des category-bundles

### ISSUE THREAD

**Issue by srhinow** [heimrichhannot/contao-api-bundle#8]
composer bemängelt das das contao-api-bundle das contao-category-bundle 1.0-beta als rewuire drin stehen hat es aber nur Versionen wie 1.0.0-beta etc gibt.

**Comment by koertho** [comment]
@srhinow Grundsätzlich bitte immer Contao-Version, PHP-Version und Versionen der Erweiterungen angeben!
Du hast in deiner composer.json (die von deinem Projekt) sicher minimum stability auf stable stehen, daher update mal diese zwei Einträge:

```
"minimum-stability": "dev",
"prefer-stable": true,
```
